services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dataset-agent-app
    restart: unless-stopped
    ports:
      - "3005:3000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    env_file:
      - .env.production
    networks:
      - app-network
    volumes:
      - uploads-data:/app/uploads

volumes:
  uploads-data:

networks:
  app-network:
    driver: bridge
